# Generated by Django 4.1.7 on 2023-03-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imageboard",
            fields=[
                (
                    "initials",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=200)),
                ("banner_image", models.ImageField(upload_to="imageboard_banners/")),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(default="Anonymous", max_length=30)),
                ("title", models.CharField(max_length=50)),
                ("body", models.TextField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(upload_to="thread_images/")),
                (
                    "imageboard",
                    models.ForeignKey(
                        db_column="initials",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.imageboard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.CharField(default="Anonymous", max_length=30)),
                ("body", models.TextField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(upload_to="reply_images/")),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.thread"
                    ),
                ),
            ],
        ),
    ]
